#!/usr/bin/env bash
#This script displays:
#The content of the current directory In a list format
#Where only the part of the name after the first dash is displayed
content="$(ls -a)"
for i in content
do
    echo $content
done